# Generated by Django 4.0.3 on 2022-04-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('premioGanado', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
