# Generated by Django 4.0.3 on 2022-04-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegoPreguntasApp', '0002_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, max_length=200, null=True)),
                ('verdadera', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregunta_respuesta', to='juegoPreguntasApp.pregunta')),
            ],
        ),
    ]
